# Generated by Django 6.1.1 on 2026-10-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=2048),
        ),
    ]
