# Generated by Django 6.1.1 on 2026-10-04 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shorturl_original_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='shortener.shorturl')),
            ],
        ),
    ]
